version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    # restart: unless-stopped

  migrator:
    container_name: migrator
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      DOCKER_ENV: true
    depends_on:
      - postgres
    entrypoint: ["/app/migrator", "--migrations-path", "/app/migrations"]

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      DOCKER_ENV: true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres
      - migrator
    # restart: unless-stopped
    command: ["/app/server", "--config", "/app/config/local.yaml"]

volumes:
  pg-data: